# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 450)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/olx.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)    #CHANGE
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_1 = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout_1.setObjectName("gridLayout_1")
        self.dataLayout_1 = QtWidgets.QGridLayout()
        self.dataLayout_1.setObjectName("dataLayout_1")
        self.id_input_1 = QtWidgets.QLineEdit(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.id_input_1.setFont(font)
        self.id_input_1.setText("")
        self.id_input_1.setObjectName("id_input_1")
        self.dataLayout_1.addWidget(self.id_input_1, 0, 3, 1, 1)
        self.date_input_1 = QtWidgets.QLineEdit(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.date_input_1.setFont(font)
        self.date_input_1.setObjectName("date_input_1")
        self.dataLayout_1.addWidget(self.date_input_1, 0, 5, 1, 1)
        self.date_name_1 = QtWidgets.QLabel(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.date_name_1.setFont(font)
        self.date_name_1.setObjectName("date_name_1")
        self.dataLayout_1.addWidget(self.date_name_1, 0, 4, 1, 1)
        self.id_name_1 = QtWidgets.QLabel(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.id_name_1.setFont(font)
        self.id_name_1.setObjectName("id_name_1")
        self.dataLayout_1.addWidget(self.id_name_1, 0, 2, 1, 1)
        self.sheet_input_1 = QtWidgets.QLineEdit(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sheet_input_1.setFont(font)
        self.sheet_input_1.setObjectName("sheet_input_1")
        self.dataLayout_1.addWidget(self.sheet_input_1, 0, 1, 1, 1)
        self.sheet_name_1 = QtWidgets.QLabel(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sheet_name_1.setFont(font)
        self.sheet_name_1.setObjectName("sheet_name_1")
        self.dataLayout_1.addWidget(self.sheet_name_1, 0, 0, 1, 1)
        self.time_name_1 = QtWidgets.QLabel(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.time_name_1.setFont(font)
        self.time_name_1.setObjectName("time_name_1")
        self.dataLayout_1.addWidget(self.time_name_1, 1, 0, 1, 1)
        self.time_input_1 = QtWidgets.QLineEdit(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.time_input_1.setFont(font)
        self.time_input_1.setObjectName("time_input_1")
        self.dataLayout_1.addWidget(self.time_input_1, 1, 1, 1, 1)
        self.tariff_name_1 = QtWidgets.QLabel(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tariff_name_1.setFont(font)
        self.tariff_name_1.setObjectName("tariff_name_1")
        self.dataLayout_1.addWidget(self.tariff_name_1, 1, 2, 1, 1)
        self.tariff_input_1 = QtWidgets.QLineEdit(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tariff_input_1.setFont(font)
        self.tariff_input_1.setObjectName("tariff_input_1")
        self.dataLayout_1.addWidget(self.tariff_input_1, 1, 3, 1, 1)
        self.service_name_1 = QtWidgets.QLabel(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.service_name_1.setFont(font)
        self.service_name_1.setObjectName("service_name_1")
        self.dataLayout_1.addWidget(self.service_name_1, 1, 4, 1, 1)
        self.service_input_1 = QtWidgets.QLineEdit(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.service_input_1.setFont(font)
        self.service_input_1.setObjectName("service_input_1")
        self.dataLayout_1.addWidget(self.service_input_1, 1, 5, 1, 1)
        self.gridLayout_1.addLayout(self.dataLayout_1, 1, 0, 1, 9)
        self.advertise_output = QtWidgets.QTextBrowser(self.tab_1)
        self.advertise_output.setObjectName("advertise_output")
        self.gridLayout_1.addWidget(self.advertise_output, 4, 0, 1, 9)
        self.menuLayout_1 = QtWidgets.QHBoxLayout()
        self.menuLayout_1.setObjectName("menuLayout_1")
        self.advertise_start = QtWidgets.QPushButton(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.advertise_start.setFont(font)
        self.advertise_start.setObjectName("advertise_start")
        self.menuLayout_1.addWidget(self.advertise_start)
        self.advertise_stop = QtWidgets.QPushButton(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.advertise_stop.setFont(font)
        self.advertise_stop.setObjectName("advertise_stop")
        self.advertise_stop.setEnabled(False)                    #CHANGE
        self.menuLayout_1.addWidget(self.advertise_stop)
        self.path_name_1 = QtWidgets.QLabel(self.tab_1)
        self.path_name_1.setObjectName("path_name_1")
        self.menuLayout_1.addWidget(self.path_name_1)
        self.path_input_1 = QtWidgets.QLineEdit(self.tab_1)
        self.path_input_1.setObjectName("path_input_1")
        self.menuLayout_1.addWidget(self.path_input_1)
        self.path_button_1 = QtWidgets.QPushButton(self.tab_1)
        self.path_button_1.setObjectName("path_button_1")
        self.menuLayout_1.addWidget(self.path_button_1)
        self.gridLayout_1.addLayout(self.menuLayout_1, 6, 0, 1, 9)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.menuLayout_2 = QtWidgets.QHBoxLayout()
        self.menuLayout_2.setObjectName("menuLayout_2")
        self.statistic_start = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.statistic_start.setFont(font)
        self.statistic_start.setObjectName("statistic_start")
        self.menuLayout_2.addWidget(self.statistic_start)
        self.statistic_stop = QtWidgets.QPushButton(self.tab_2)
        self.statistic_stop.setObjectName("statistic_stop")
        self.statistic_stop.setEnabled(False)                    #CHANGE
        self.menuLayout_2.addWidget(self.statistic_stop)
        self.path_name_2 = QtWidgets.QLabel(self.tab_2)
        self.path_name_2.setObjectName("path_name_2")
        self.menuLayout_2.addWidget(self.path_name_2)
        self.path_input_2 = QtWidgets.QLineEdit(self.tab_2)
        self.path_input_2.setObjectName("path_input_2")
        self.menuLayout_2.addWidget(self.path_input_2)
        self.path_button_2 = QtWidgets.QPushButton(self.tab_2)
        self.path_button_2.setObjectName("path_button_2")
        self.menuLayout_2.addWidget(self.path_button_2)
        self.gridLayout_2.addLayout(self.menuLayout_2, 8, 0, 2, 6)
        self.statistic_output = QtWidgets.QTextBrowser(self.tab_2)
        self.statistic_output.setObjectName("statistic_output")
        self.gridLayout_2.addWidget(self.statistic_output, 3, 0, 1, 6)
        self.dataLayout_2 = QtWidgets.QHBoxLayout()
        self.dataLayout_2.setObjectName("dataLayout_2")
        self.sheet_name_2 = QtWidgets.QLabel(self.tab_2)
        self.sheet_name_2.setObjectName("sheet_name_2")
        self.dataLayout_2.addWidget(self.sheet_name_2)
        self.sheet_input_2 = QtWidgets.QLineEdit(self.tab_2)
        self.sheet_input_2.setObjectName("sheet_input_2")
        self.dataLayout_2.addWidget(self.sheet_input_2)
        self.id_name_2 = QtWidgets.QLabel(self.tab_2)
        self.id_name_2.setObjectName("id_name_2")
        self.dataLayout_2.addWidget(self.id_name_2)
        self.id_input_2 = QtWidgets.QLineEdit(self.tab_2)
        self.id_input_2.setObjectName("id_input_2")
        self.dataLayout_2.addWidget(self.id_input_2)
        self.gridLayout_2.addLayout(self.dataLayout_2, 0, 0, 1, 6)
        self.stat_bar = QtWidgets.QProgressBar(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stat_bar.sizePolicy().hasHeightForWidth())
        self.stat_bar.setSizePolicy(sizePolicy)
        self.stat_bar.setAlignment(QtCore.Qt.AlignCenter)
        self.stat_bar.setObjectName("stat_bar")
        self.stat_bar.setRange(0, 100)
        self.stat_bar.setVisible(False)                                                   #CHANGE
        self.gridLayout_2.addWidget(self.stat_bar, 7, 0, 1, 6)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.dataLayout_3 = QtWidgets.QHBoxLayout()
        self.dataLayout_3.setObjectName("dataLayout_3")
        self.sheet_name_3 = QtWidgets.QLabel(self.tab_3)
        self.sheet_name_3.setObjectName("sheet_name_3")
        self.dataLayout_3.addWidget(self.sheet_name_3)
        self.sheet_input_3 = QtWidgets.QLineEdit(self.tab_3)
        self.sheet_input_3.setObjectName("sheet_input_3")
        self.dataLayout_3.addWidget(self.sheet_input_3)
        self.id_name_3 = QtWidgets.QLabel(self.tab_3)
        self.id_name_3.setObjectName("id_name_3")
        self.dataLayout_3.addWidget(self.id_name_3)
        self.id_input_3 = QtWidgets.QLineEdit(self.tab_3)
        self.id_input_3.setObjectName("id_input_3")
        self.dataLayout_3.addWidget(self.id_input_3)
        self.gridLayout_3.addLayout(self.dataLayout_3, 0, 0, 1, 1)
        self.menuLayout_3 = QtWidgets.QHBoxLayout()
        self.menuLayout_3.setObjectName("menuLayout_3")
        self.raise_start = QtWidgets.QPushButton(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.raise_start.setFont(font)
        self.raise_start.setObjectName("raise_start")
        self.menuLayout_3.addWidget(self.raise_start)
        self.raise_stop = QtWidgets.QPushButton(self.tab_3)
        self.raise_stop.setObjectName("raise_stop")
        self.raise_stop.setEnabled(False)                    #CHANGE
        self.menuLayout_3.addWidget(self.raise_stop)
        self.path_name_3 = QtWidgets.QLabel(self.tab_3)
        self.path_name_3.setObjectName("path_name_3")
        self.menuLayout_3.addWidget(self.path_name_3)
        self.path_input_3 = QtWidgets.QLineEdit(self.tab_3)
        self.path_input_3.setObjectName("path_input_3")
        self.menuLayout_3.addWidget(self.path_input_3)
        self.path_button_3 = QtWidgets.QPushButton(self.tab_3)
        self.path_button_3.setObjectName("path_button_3")
        self.menuLayout_3.addWidget(self.path_button_3)
        self.gridLayout_3.addLayout(self.menuLayout_3, 3, 0, 1, 1)
        self.raise_output = QtWidgets.QTextBrowser(self.tab_3)
        self.raise_output.setObjectName("raise_output")
        self.gridLayout_3.addWidget(self.raise_output, 1, 0, 1, 1)
        self.up_bar = QtWidgets.QProgressBar(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.up_bar.sizePolicy().hasHeightForWidth())
        self.up_bar.setSizePolicy(sizePolicy)
        self.up_bar.setAlignment(QtCore.Qt.AlignCenter)
        self.up_bar.setObjectName("up_bar")
        self.up_bar.setRange(0, 100)
        self.up_bar.setVisible(False)                                                    #CHANGE
        self.gridLayout_3.addWidget(self.up_bar, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.dataLayout_4 = QtWidgets.QGridLayout()
        self.dataLayout_4.setObjectName("dataLayout_4")
        self.time_input_4 = QtWidgets.QLineEdit(self.tab_4)
        self.time_input_4.setObjectName("time_input_4")
        self.dataLayout_4.addWidget(self.time_input_4, 1, 1, 1, 1)
        self.date_input_4 = QtWidgets.QLineEdit(self.tab_4)
        self.date_input_4.setObjectName("date_input_4")
        self.dataLayout_4.addWidget(self.date_input_4, 1, 3, 1, 1)
        self.date_name_4 = QtWidgets.QLabel(self.tab_4)
        self.date_name_4.setObjectName("date_name_4")
        self.dataLayout_4.addWidget(self.date_name_4, 1, 2, 1, 1)
        self.time_name_4 = QtWidgets.QLabel(self.tab_4)
        self.time_name_4.setObjectName("time_name_4")
        self.dataLayout_4.addWidget(self.time_name_4, 1, 0, 1, 1)
        self.sheet_name_4 = QtWidgets.QLabel(self.tab_4)
        self.sheet_name_4.setObjectName("sheet_name_4")
        self.dataLayout_4.addWidget(self.sheet_name_4, 0, 0, 1, 1)
        self.sheet_input_4 = QtWidgets.QLineEdit(self.tab_4)
        self.sheet_input_4.setObjectName("sheet_input_4")
        self.dataLayout_4.addWidget(self.sheet_input_4, 0, 1, 1, 1)
        self.id_name_4 = QtWidgets.QLabel(self.tab_4)
        self.id_name_4.setObjectName("id_name_4")
        self.dataLayout_4.addWidget(self.id_name_4, 0, 2, 1, 1)
        self.id_input_4 = QtWidgets.QLineEdit(self.tab_4)
        self.id_input_4.setObjectName("id_input_4")
        self.dataLayout_4.addWidget(self.id_input_4, 0, 3, 1, 1)
        self.gridLayout_4.addLayout(self.dataLayout_4, 0, 0, 1, 1)
        self.activate_output = QtWidgets.QTextBrowser(self.tab_4)
        self.activate_output.setObjectName("activate_output")
        self.gridLayout_4.addWidget(self.activate_output, 1, 0, 1, 1)
        self.menuLayout_4 = QtWidgets.QHBoxLayout()
        self.menuLayout_4.setObjectName("menuLayout_4")
        self.activate_start = QtWidgets.QPushButton(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.activate_start.setFont(font)
        self.activate_start.setObjectName("activate_start")
        self.menuLayout_4.addWidget(self.activate_start)
        self.activate_stop = QtWidgets.QPushButton(self.tab_4)
        self.activate_stop.setObjectName("activate_stop")
        self.activate_stop.setEnabled(False)                    #CHANGE
        self.menuLayout_4.addWidget(self.activate_stop)
        self.path_name_4 = QtWidgets.QLabel(self.tab_4)
        self.path_name_4.setObjectName("path_name_4")
        self.menuLayout_4.addWidget(self.path_name_4)
        self.path_input_4 = QtWidgets.QLineEdit(self.tab_4)
        self.path_input_4.setObjectName("path_input_4")
        self.menuLayout_4.addWidget(self.path_input_4)
        self.path_button_4 = QtWidgets.QPushButton(self.tab_4)
        self.path_button_4.setObjectName("path_button_4")
        self.menuLayout_4.addWidget(self.path_button_4)
        self.gridLayout_4.addLayout(self.menuLayout_4, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 4)
        self.loginLayout = QtWidgets.QGridLayout()
        self.loginLayout.setObjectName("loginLayout")
        self.login_output = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.login_output.setFont(font)
        self.login_output.setObjectName("login_output")
        self.loginLayout.addWidget(self.login_output, 1, 1, 2, 1)
        self.login_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.login_button.setFont(font)
        self.login_button.setObjectName("login_button")
        self.loginLayout.addWidget(self.login_button, 1, 2, 1, 1)
        self.settings_button = QtWidgets.QToolButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.settings_button.setFont(font)
        self.settings_button.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.settings_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)             #CHANGE
        self.settings_button.setIcon(icon1)
        self.settings_button.setIconSize(QtCore.QSize(16, 16))
        self.settings_button.setCheckable(False)
        self.settings_button.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.settings_button.setAutoRaise(True)
        self.settings_button.setArrowType(QtCore.Qt.NoArrow)
        self.settings_button.setObjectName("settings_button")
        self.loginLayout.addWidget(self.settings_button, 2, 2, 1, 1)
        self.gridLayout.addLayout(self.loginLayout, 1, 1, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dockWidget.setFont(font)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_settings = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_settings.setObjectName("gridLayout_settings")
        self.version = QtWidgets.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.version.setFont(font)
        self.version.setText("")
        self.version.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.version.setObjectName("version")
        self.gridLayout_settings.addWidget(self.version, 9, 0, 1, 1)
        self.user_id_input = QtWidgets.QLineEdit(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.user_id_input.setFont(font)
        self.user_id_input.setObjectName("user_id_input")
        reg = QtCore.QRegExp("[0-9]{18}")                       #CHANGE
        pValidator = QtGui.QRegExpValidator(self)               #CHANGE
        pValidator.setRegExp(reg)                               #CHANGE
        self.user_id_input.setValidator(pValidator)             #CHANGE
        self.gridLayout_settings.addWidget(self.user_id_input, 1, 0, 1, 1)
        self.sound_button = QtWidgets.QCheckBox(self.dockWidgetContents)
        self.sound_button.setObjectName("sound_button")
        self.gridLayout_settings.addWidget(self.sound_button, 2, 0, 1, 1)
        self.password_label = QtWidgets.QLabel(self.dockWidgetContents)
        self.password_label.setObjectName("password_label")
        self.gridLayout_settings.addWidget(self.password_label, 5, 0, 1, 1)
        self.login_label = QtWidgets.QLabel(self.dockWidgetContents)
        self.login_label.setObjectName("login_label")
        self.gridLayout_settings.addWidget(self.login_label, 3, 0, 1, 1)
        self.login_input = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.login_input.setObjectName("login_input")
        self.gridLayout_settings.addWidget(self.login_input, 4, 0, 1, 1)
        self.password_input = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.password_input.setObjectName("password_input")
        self.gridLayout_settings.addWidget(self.password_input, 6, 0, 1, 1)
        self.user_id_label = QtWidgets.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.user_id_label.setFont(font)
        self.user_id_label.setObjectName("user_id_label")
        self.gridLayout_settings.addWidget(self.user_id_label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_settings.addItem(spacerItem, 7, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.dockWidget.setVisible(False)                               #CHANGE
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)                               #CHANGE
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.sheet_input_1)
        MainWindow.setTabOrder(self.sheet_input_1, self.id_input_1)
        MainWindow.setTabOrder(self.id_input_1, self.date_input_1)
        MainWindow.setTabOrder(self.date_input_1, self.time_input_1)
        MainWindow.setTabOrder(self.time_input_1, self.tariff_input_1)
        MainWindow.setTabOrder(self.tariff_input_1, self.service_input_1)
        MainWindow.setTabOrder(self.service_input_1, self.advertise_output)
        MainWindow.setTabOrder(self.advertise_output, self.advertise_stop)
        MainWindow.setTabOrder(self.advertise_stop, self.path_input_1)
        MainWindow.setTabOrder(self.path_input_1, self.path_button_1)
        MainWindow.setTabOrder(self.path_button_1, self.sheet_input_2)
        MainWindow.setTabOrder(self.sheet_input_2, self.id_input_2)
        MainWindow.setTabOrder(self.id_input_2, self.statistic_output)
        MainWindow.setTabOrder(self.statistic_output, self.path_input_2)
        MainWindow.setTabOrder(self.path_input_2, self.path_button_2)
        MainWindow.setTabOrder(self.path_button_2, self.sheet_input_3)
        MainWindow.setTabOrder(self.sheet_input_3, self.id_input_3)
        MainWindow.setTabOrder(self.id_input_3, self.raise_output)
        MainWindow.setTabOrder(self.raise_output, self.path_input_3)
        MainWindow.setTabOrder(self.path_input_3, self.path_button_3)
        MainWindow.setTabOrder(self.path_button_3, self.sheet_input_4)
        MainWindow.setTabOrder(self.sheet_input_4, self.id_input_4)
        MainWindow.setTabOrder(self.id_input_4, self.time_input_4)
        MainWindow.setTabOrder(self.time_input_4, self.date_input_4)
        MainWindow.setTabOrder(self.date_input_4, self.activate_output)
        MainWindow.setTabOrder(self.activate_output, self.activate_stop)
        MainWindow.setTabOrder(self.activate_stop, self.path_input_4)
        MainWindow.setTabOrder(self.path_input_4, self.path_button_4)
        MainWindow.setTabOrder(self.path_button_4, self.user_id_input)
        MainWindow.setTabOrder(self.user_id_input, self.sound_button)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OLX"))
        self.date_name_1.setText(_translate("MainWindow", "Дата"))
        self.id_name_1.setText(_translate("MainWindow", "Id"))
        self.sheet_name_1.setText(_translate("MainWindow", "Имя таблицы"))
        self.time_name_1.setText(_translate("MainWindow", "Время"))
        self.tariff_name_1.setText(_translate("MainWindow", "Тариф"))
        self.service_name_1.setText(_translate("MainWindow", "Доп. услуги"))
        self.advertise_start.setText(_translate("MainWindow", "Start"))
        self.advertise_stop.setText(_translate("MainWindow", "Stop"))
        self.path_name_1.setText(_translate("MainWindow", "Excel path"))
        self.path_button_1.setText(_translate("MainWindow", "Browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Реклама"))
        self.statistic_start.setText(_translate("MainWindow", "Start"))
        self.statistic_stop.setText(_translate("MainWindow", "Stop"))
        self.path_name_2.setText(_translate("MainWindow", "Excel path"))
        self.path_button_2.setText(_translate("MainWindow", "Browse"))
        self.sheet_name_2.setText(_translate("MainWindow", "Имя таблицы"))
        self.id_name_2.setText(_translate("MainWindow", "Id"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Статистика"))
        self.sheet_name_3.setText(_translate("MainWindow", "Имя таблицы"))
        self.id_name_3.setText(_translate("MainWindow", "Id"))
        self.raise_start.setText(_translate("MainWindow", "Start"))
        self.raise_stop.setText(_translate("MainWindow", "Stop"))
        self.path_name_3.setText(_translate("MainWindow", "Excel path"))
        self.path_button_3.setText(_translate("MainWindow", "Browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Поднятия"))
        self.date_name_4.setText(_translate("MainWindow", "Дата"))
        self.time_name_4.setText(_translate("MainWindow", "Время"))
        self.sheet_name_4.setText(_translate("MainWindow", "Имя таблицы"))
        self.id_name_4.setText(_translate("MainWindow", "Id"))
        self.activate_start.setText(_translate("MainWindow", "Start"))
        self.activate_stop.setText(_translate("MainWindow", "Stop"))
        self.path_name_4.setText(_translate("MainWindow", "Excel path"))
        self.path_button_4.setText(_translate("MainWindow", "Browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Активация"))
        self.login_button.setText(_translate("MainWindow", "Login"))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "Settings"))
        self.sound_button.setText(_translate("MainWindow", "Включить звук"))
        self.password_label.setText(_translate("MainWindow", "Password"))
        self.login_label.setText(_translate("MainWindow", "Login"))
        self.user_id_label.setText(_translate("MainWindow", "User ID"))
